FilmStoreWithMobile/WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
namespace WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        IFilmRepository repository;

        public AdminController(IFilmRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Films);
        }
        public ViewResult Edit(int filmId)
        {
            Film film = repository.Films
                .FirstOrDefault(g => g.FilmId == filmId);
            return View(film);
        }
        [HttpPost]
        public ActionResult Edit(Film film, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    film.ImageMimeType = image.ContentType;
                    film.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(film.ImageData, 0, image.ContentLength);
                }
                repository.SaveFilm(film);
                TempData["message"] = string.Format("Изменения в фильме \"{0}\" были сохранены", film.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // Что-то не так со значениями данных
                return View(film);
            }
        }
        public ViewResult Create()
        {
            return View("Edit", new Film());
        }
        [HttpPost]
        public ActionResult Delete(int filmId)
        {
            Film deletedFilm = repository.DeleteFilm(filmId);
            if (deletedFilm != null)
            {
                TempData["message"] = string.Format("Фильм \"{0}\" был удален",
                    deletedFilm.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

FilmStoreWithMobile/WebUI/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class FilmController : Controller
    {
        private IFilmRepository repository;
        public int pageSize = 3;
        public FilmController(IFilmRepository repo)
        {
            repository = repo;
        }
        public ViewResult List(string genre, int page = 1)
        {
            FilmListViewModel model = new FilmListViewModel
            {
                Films = repository.Films
                .Where(p => genre == null || p.Genre == genre)
                .OrderBy(Film => Film.FilmId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = genre == null ?
                    repository.Films.Count():
                    repository.Films.Where(film=>film.Genre==genre).Count()
                },
                CurrentGenre = genre

            };
            return View(model);
        }
        public FileContentResult GetImage(int filmId)
        {
            Film film = repository.Films
                .FirstOrDefault(g => g.FilmId == filmId);

            if (film != null)
            {
                return File(film.ImageData, film.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

FilmStoreWithMobile/WebUI/Views/Admin/Edit.cshtml
@model Domain.Entities.Film

@{
    ViewBag.Title = "Админ панель: редактирование товара";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Редактирование фильма «@Model.Name»</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin",
        FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.FilmId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "FilmId":
                    case "ImageData":
                    case "ImageMimeType":
                        // Ничего не делать
                        break;
                    default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @if (property.PropertyName == "Description")
                            {
                                @Html.TextArea(property.PropertyName, null,
                                    new { @class = "form-control", rows = 5 })
                            }
                            else
                            {
                                @Html.TextBox(property.PropertyName, null,
                                    new { @class = "form-control" })
                            }
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;
                }
            }
            <div class="form-group">
                <div style="position:relative;">
                    <label>Картинка</label>
                    <a class='btn' href='javascript:;'>
                        Выберите файл...
                        <input type="file" name="Image" size="40"
                               style="position:absolute;z-index:2;top:0;
                                left:0;filter: alpha(opacity=0); opacity:0;
                                background-color:transparent;color:transparent;"
                               onchange='$("#upload-file-info").html($(this).val());'>
                    </a>
                    <span class='label label-info' id="upload-file-info"></span>
                </div>
                @if (Model.ImageData == null)
                {
                    <div class="form-control-static">Нет картинки</div>
                }
                else
                {
                    <img class="img-thumbnail" width="150" height="150"
                         src="@Url.Action("GetImage", "Film",
                        new { Model.FilmId })" />
                }
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
            @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
            {
                @class = "btn btn-default"
            })
        </div>
    }
</div>

FilmStoreWithMobile/WebUI/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Film>

@{
    ViewBag.Title = "Админ панель : список товаров";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Список фильмов</h3>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-condensed table-bordered">
                <tr>
                    <th class="text-right">ID</th>
                    <th>Название</th>
                    <th class="text-right">Цена</th>
                    <th class="text-center">Действия</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-right">@item.FilmId</td>
                        <td>@Html.ActionLink(item.Name, "Edit", new { item.FilmId })</td>
                        <td class="text-right">@item.Price.ToString("#.## руб")</td>
                        <td class="text-center">
                            @using (Html.BeginForm("Delete", "Admin"))
                            {
                                @Html.Hidden("FilmId", item.FilmId)
                                <input type="submit"
                                       class="btn btn-default btn-xs"
                                       value="Удалить" />
                            }
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="panel-footer">
            @Html.ActionLink("Добавить фильм", "Create", null,
                new { @class = "btn btn-default" })
        </div>
    </div>