FilmStore/WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;


namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IFilmRepository repository;

        public NavController(IFilmRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string genre=null)
        {
            ViewBag.SelectedGenre = genre;

            IEnumerable<string> genres = repository.Films
                .Select(film => film.Genre)
                .Distinct()
                .OrderBy(x => x);
           
            return PartialView("FlexMenu", genres);
        }
        
    }
}

FilmStore/WebUI/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart


<div class="navbar-right hidden-xs">
    @Html.ActionLink("Заказать", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-right visible-xs">
    <a href=@Url.Action("Index", "Cart", new { returnUrl = Request.Url.PathAndQuery })
       class="btn btn-default navbar-btn">
        <span class="glyphicon glyphicon-shopping-cart"></span>
    </a>
</div>

<div class="navbar-text navbar-right">
    <b class="hidden-xs">Ваша корзина:</b>
    @Model.Lines.Sum(x => x.Quantity) фильмов,
    @Model.ComputeTotalValue().ToString("#.## руб")
</div>

FilmStore/WebUI/Views/Nav/FlexMenu.Mobile.cshtml
@model IEnumerable<string>

<div data-role="navbar">
    <ul>
        @foreach (var link in Model)
        {
            <li>
                @Html.RouteLink(link, new
                {
                    controller = "Film",
                    action = "List",
                    genre = link,
                    page = 1
                }, new
                {
                    data_transition = "fade",
                    @class = (link == ViewBag.SelectedGenre ? "ui-btn-active" : null)
                })
            </li>
        }
    </ul>
</div>

FilmStore/WebUI/Views/Nav/FlexMenu.cshtml
@model IEnumerable<string>

@{
    bool horizontal = ((bool)(ViewContext.RouteData.Values["horizontalNav"] ?? false));
    string wrapperClasses = horizontal ? "btn-group btn-group-sm btn-group-justified" : null;
}

<div class="@wrapperClasses">

    @Html.ActionLink("Домой", "List", "Film", null,
    new
    {
        @class = horizontal ? "btn btn-default btn-sm" :
            "btn btn-block btn-default btn-lg"
    })

    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new
        {
            controller = "Film",
            action = "List",
            genre = link,
            page = 1
        }, new
        {
            @class = (horizontal ? "btn btn-default btn-sm"
                : "btn btn-block btn-default btn-lg")
                + (link == ViewBag.SelectedGenre ? " btn-primary" : "")
        })
    }

</div>

FilmStore/WebUI/Views/Nav/MenuHorizontal.cshtml
@model IEnumerable<string>

<div class="btn-group btn-group-sm btn-group-justified">
    @Html.ActionLink("Домой", "List", "Film", null, new { @class = "btn btn-default btn-sm" })

    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new
        {
            controller = "Film",
            action = "List",
            genre = link,
            page = 1
        }, new
        {
            @class = "btn btn-default btn-sm"
                    + (link == ViewBag.SelectedGenre ? " btn-primary" : "")
        })
    }
</div>

FilmStore/WebUI/Views/Shared/FilmSummary.Mobile.cshtml
@model Domain.Entities.Film

<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>@Model.Name</h2>
    <div>
        <div>
            @Model.Description
        </div>
        <div>
            <strong>(@Model.Price.ToString("#.## руб"))</strong>
        </div>
        <div>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.HiddenFor(x => x.FilmId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="В корзину" />
            }
        </div>
    </div>
</div>

FilmStore/WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>Киноман</h3>
            @Html.Action("Menu", "Nav")
        </div>
        <div data-role="content">
            <ul data-role="listview" data-divider-theme="b" data-inset="false">
                @RenderBody()
            </ul>
        </div>
    </div>
</body>
</html>

FilmStore/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
    </style>
</head>
<body>

    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs">магазин фильмов Киноман</span>
            <div class="visible-xs">Киноман</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { horizontalNav = true })
    </div>
    <div class="row panel">
        <div id="genres" class="col-sm-3 hidden-xs">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>